#pragma once

/**
 * @file SimpleASTBuilder.h
 * @brief AST builder that converts ANTLR4 parse trees to typed AST nodes.
 *
 * @section Purpose
 * SimpleASTBuilder is responsible for traversing ANTLR4 parse trees (generated from
 * the Hooc grammar in Hooc.g4) and constructing a typed Abstract Syntax Tree (AST).
 * This is the second stage of the Hooc compilation pipeline:
 *
 *   Source Code (.hoo)
 *       ↓
 *   [ANTLR4 Lexer/Parser] → Parse Tree
 *       ↓
 *   [SimpleASTBuilder] → Typed AST
 *       ↓
 *   [HVMCodeGenerator] → HVM Bytecode
 *
 * @section Responsibility
 * - Convert ANTLR4 parse tree contexts to strongly-typed AST nodes
 * - Handle all grammar elements: declarations, statements, expressions, types
 * - Support Hooc language features: classes, functions, control flow,
 *   arrays, optional/nullable types, string interpolation, 'this' keyword
 * - Validate grammar constraints (e.g., single constructor per class)
 *
 * @section Usage
 * Create a SimpleASTBuilder instance and call buildAST() with a CompilationUnitContext:
 *
 * @code
 * SimpleASTBuilder builder;
 * auto ast = builder.buildAST(compilationUnitContext);
 * @endcode
 *
 * The returned CompilationUnit contains all imports and declarations with full type information.
 *
 * @see Hooc.g4 for the grammar definition
 * @see AST.h for all available AST node types
 */

#include "AST.h"
#include "HoocBaseVisitor.h"

namespace hooc {

/**
 * @brief Builds a typed AST from an ANTLR4 parse tree.
 *
 * This class implements the visitor pattern to traverse the parse tree
 * generated by ANTLR4 and construct corresponding AST nodes.
 */
class SimpleASTBuilder {
public:
    /**
     * @brief Entry point: builds a complete CompilationUnit AST.
     * @param ctx The compilation unit context from ANTLR4 parser.
     * @return Unique pointer to the built CompilationUnit, or nullptr on failure.
     */
    std::unique_ptr<ast::CompilationUnit> buildAST(HoocParser::CompilationUnitContext* ctx);

    // ===== Helper Methods (Public for testing) =====

    /**
     * @brief Converts a type name string to PrimitiveTypeKind enum.
     * @param typeName String like "int64", "string", etc.
     * @return The corresponding PrimitiveTypeKind.
     */
    ast::PrimitiveTypeKind getPrimitiveTypeKind(const std::string& typeName);

    /**
     * @brief Parses integer literal token.
     * @param node INTEGER_LITERAL terminal node.
     * @return The parsed integer value.
     */
    int64_t getIntValue(antlr4::tree::TerminalNode* node);

    /**
     * @brief Parses floating point literal token.
     * @param node FLOATING_LITERAL terminal node.
     * @return The parsed double value.
     */
    double getDoubleValue(antlr4::tree::TerminalNode* node);

    /**
     * @brief Parses f8 literal token, returning its promoted f64 value.
     */
    double getF8Value(antlr4::tree::TerminalNode* node);

    /**
     * @brief Parses bit literal token.
     */
    int64_t getBitValue(antlr4::tree::TerminalNode* node);

    /**
     * @brief Extracts codepoint from CHAR_LITERAL token.
     * @param node CHAR_LITERAL terminal node.
     * @return The Unicode codepoint value.
     */
    int64_t getCharValue(antlr4::tree::TerminalNode* node);

    /**
     * @brief Extracts string value from STRING_LITERAL token (removes quotes).
     * @param node STRING_LITERAL terminal node.
     * @return The unquoted string value.
     */
    std::string getStringValue(antlr4::tree::TerminalNode* node);

    /**
     * @brief Extracts binary operator from a terminal node.
     * @param node Terminal node containing operator.
     * @return The corresponding BinaryOperator enum value.
     */
    ast::BinaryOperator getBinaryOperator(antlr4::tree::TerminalNode* node);

    /**
     * @brief Parses boolean literal token.
     * @param node TRUE or FALSE terminal node.
     * @return The boolean value.
     */
    bool getBoolValue(antlr4::tree::TerminalNode* node);

    /**
     * @brief Checks if a string literal contains interpolation syntax.
     * Detects ${...} patterns indicating an interpolated string.
     * @param node STRING_LITERAL terminal node.
     * @return true if the string contains ${...}, false otherwise.
     */
    bool isInterpolatedString(antlr4::tree::TerminalNode* node);

    /**
     * @brief Builds an Expression from any expression context.
     * Entry point for expression building (delegates to assignmentExpression).
     * @param ctx Expression context.
     * @return Unique pointer to the built Expression.
     */
    std::unique_ptr<ast::Expression> buildExpression(HoocParser::ExpressionContext* ctx);

    /**
     * @brief Parses an interpolated string into its parts.
     * @param templateText The raw string containing placeholders.
     * @return A vector of InterpolatedString::Part.
     */
    std::vector<ast::InterpolatedString::Part> parseInterpolatedString(const std::string& templateText);

private:
    // ===== Declaration Building =====

    /**
     * @brief Builds a Declaration from any declaration context.
     * @param ctx Declaration context (function, class, or variable).
     * @return The appropriate Declaration subtype, or nullptr.
     */
    std::unique_ptr<ast::Declaration> buildDeclaration(HoocParser::DeclarationContext* ctx);

    /**
     * @brief Builds a FunctionDeclaration from its context.
     * @param ctx Function declaration context.
     * @return Unique pointer to FunctionDeclaration.
     */
    std::unique_ptr<ast::FunctionDeclaration> buildFunctionDeclaration(HoocParser::FunctionDeclarationContext* ctx);

    /**
     * @brief Builds a FunctionDeclaration with modifiers (for member functions).
     * @param ctx Function declaration context.
     * @param modifiers Function modifiers.
     * @return Unique pointer to FunctionDeclaration.
     */
    std::unique_ptr<ast::FunctionDeclaration> buildFunctionDeclaration(
        HoocParser::FunctionDeclarationContext* ctx,
        std::vector<ast::FunctionModifier> modifiers);

    /**
     * @brief Converts a functionModifier context to FunctionModifier enum.
     * @param ctx Function modifier context.
     * @return The corresponding FunctionModifier value.
     */
    ast::FunctionModifier getFunctionModifier(HoocParser::FunctionModifierContext* ctx);

    /**
     * @brief Builds a VariableDeclaration from its context.
     * Handles both explicit types and type inference.
     * @param ctx Variable declaration context.
     * @return Unique pointer to VariableDeclaration.
     */
    std::unique_ptr<ast::VariableDeclaration> buildVariableDeclaration(HoocParser::VariableDeclarationContext* ctx,
        std::vector<ast::FunctionModifier> modifiers = {});

    /**
     * @brief Builds a ConstantDeclaration from its context.
     * @param ctx Constant declaration context.
     * @return Unique pointer to VariableDeclaration (marked as constant).
     */
    std::unique_ptr<ast::VariableDeclaration> buildConstantDeclaration(HoocParser::ConstantDeclarationContext* ctx);


    /**
     * @brief Builds a VariableDeclarationStatement (variable with trailing semicolon).
     * @param ctx Variable declaration statement context.
     * @return Unique pointer to VariableDeclarationStatement.
     */
    std::unique_ptr<ast::VariableDeclarationStatement> buildVariableDeclarationStatement(HoocParser::VariableDeclarationStatementContext* ctx);

    /**
     * @brief Builds a ClassDeclaration from its context.
     * Extracts modifiers, base class, and class body.
     * @param ctx Class declaration context.
     * @return Unique pointer to ClassDeclaration.
     */
    std::unique_ptr<ast::ClassDeclaration> buildClassDeclaration(HoocParser::ClassDeclarationContext* ctx);

    // ===== Type Building =====

    /**
     * @brief Builds a Type from any type context.
     * Handles union types, optional types, and array types.
     * @param ctx Type context.
     * @return Unique pointer to the appropriate Type subtype.
     */
    std::unique_ptr<ast::Type> buildType(HoocParser::TypeContext* ctx);

    /**
     * @brief Builds an OptionalType (with optional ? suffix).
     * @param ctx Optional type context.
     * @return Unique pointer to OptionalType, or nullptr on failure.
     */
    std::unique_ptr<ast::OptionalType> buildOptionalType(HoocParser::OptionalTypeContext* ctx);

    /**
     * @brief Builds an ArrayType (e.g., int64[] or string[][]).
     * @param ctx Array type context.
     * @return Unique pointer to ArrayType.
     */
    std::unique_ptr<ast::ArrayType> buildArrayType(HoocParser::ArrayTypeContext* ctx);

    /**
     * @brief Builds a BaseType from primitive or qualified type.
     * @param ctx Base type context.
     * @return Unique pointer to BaseType.
     */
    std::unique_ptr<ast::BaseType> buildBaseType(HoocParser::BaseTypeContext* ctx);

    /**
     * @brief Builds a PrimitiveType from its keyword.
     * @param ctx Primitive type context.
     * @return Unique pointer to PrimitiveType.
     */
    std::unique_ptr<ast::PrimitiveType> buildPrimitiveType(HoocParser::PrimitiveTypeContext* ctx);

    /**
     * @brief Builds a MapType (map[K, V] where K is restricted key type).
     * @param ctx Map type context.
     * @return Unique pointer to MapType.
     */
    std::unique_ptr<ast::MapType> buildMapType(HoocParser::MapTypeContext* ctx);

    std::unique_ptr<ast::HashMapType> buildHashMapType(HoocParser::HashMapTypeContext* ctx);

    /**
     * @brief Builds a FutureType (Future<T>).
     * @param ctx Future type context.
     * @return Unique pointer to FutureType.
     */
    std::unique_ptr<ast::FutureType> buildFutureType(HoocParser::FutureTypeContext* ctx);

    /**
     * @brief Builds a TensorType (tensor[T][d0, d1, d2]).
     * @param ctx Tensor type context.
     * @return Unique pointer to TensorType.
     */
    std::unique_ptr<ast::TensorType> buildTensorType(HoocParser::TensorTypeContext* ctx);

    // ===== Statement Building =====

    /**
     * @brief Builds a Statement from any statement context.
     * @param ctx Statement context (block, variable decl, if, while, for, scope, etc.).
     * @return The appropriate Statement subtype, or nullptr.
     */
    std::unique_ptr<ast::Statement> buildStatement(HoocParser::StatementContext* ctx);

    /**
     * @brief Builds a Block from its context.
     * @param ctx Block context (zero or more statements in braces).
     * @return Unique pointer to Block.
     */
    std::unique_ptr<ast::Block> buildBlock(HoocParser::BlockContext* ctx);

    /**
     * @brief Builds an IfStatement from its context.
     * Handles optional else block.
     * @param ctx If statement context.
     * @return Unique pointer to IfStatement.
     */
    std::unique_ptr<ast::IfStatement> buildIfStatement(HoocParser::IfStatementContext* ctx);

    /**
     * @brief Builds a WhileStatement from its context.
     * @param ctx While statement context.
     * @return Unique pointer to WhileStatement.
     */
    std::unique_ptr<ast::WhileStatement> buildWhileStatement(HoocParser::WhileStatementContext* ctx);

    /**
     * @brief Builds a ForInStatement from its context.
     * For syntax: for item in iterable { }
     * @param ctx For statement context.
     * @return Unique pointer to ForInStatement, or nullptr on failure.
     */
    std::unique_ptr<ast::ForInStatement> buildForInStatement(HoocParser::ForStatementContext* ctx);

    /**
     * @brief Builds a ForRangeStatement from its context.
     * For syntax: for i in start .. end { }
     * @param ctx For statement context.
     * @return Unique pointer to ForRangeStatement, or nullptr on failure.
     */
    std::unique_ptr<ast::ForRangeStatement> buildForRangeStatement(HoocParser::ForStatementContext* ctx);

    /**
     * @brief Builds a TryCatchStatement from its context.
     * try...catch...finally syntax.
     * @param ctx Try-catch statement context.
     * @return Unique pointer to TryCatchStatement.
     */
    std::unique_ptr<ast::TryCatchStatement> buildTryCatchStatement(HoocParser::TryCatchStatementContext* ctx);

    /**
     * @brief Builds a DoWhileStatement from its context.
     * do { } while(expression); syntax.
     * @param ctx Do-while statement context.
     * @return Unique pointer to DoWhileStatement.
     */
    std::unique_ptr<ast::DoWhileStatement> buildDoWhileStatement(HoocParser::DoWhileStatementContext* ctx);

    /**
     * @brief Builds a SwitchStatement from its context.
     * switch(expression) { case val: stmts... default: stmts... }
     * @param ctx Switch statement context.
     * @return Unique pointer to SwitchStatement.
     */
    std::unique_ptr<ast::SwitchStatement> buildSwitchStatement(HoocParser::SwitchStatementContext* ctx);

    /**
     * @brief Builds a ThrowStatement from its context.
     * throw expression; syntax.
     * @param ctx Throw statement context.
     * @return Unique pointer to ThrowStatement.
     */
    std::unique_ptr<ast::ThrowStatement> buildThrowStatement(HoocParser::ThrowStatementContext* ctx);

    // ===== Expression Building =====

    /**
     * @brief Builds an Expression from any expression context.
     * Entry point for expression building (delegates to assignmentExpression).
     * @param ctx Expression context.
     * @return Unique pointer to the built Expression.
     */

    /**
     * @brief Builds an AssignmentExpression.
     * @param ctx Assignment expression context.
     * @return AssignmentExpression or the inner expression if no assignment.
     */
    std::unique_ptr<ast::Expression> buildAssignmentExpression(HoocParser::AssignmentExpressionContext* ctx);

    /**
     * @brief Builds a CompoundAssignmentExpression (+=, etc.).
     * @param ctx Assignment expression context.
     * @return CompoundAssignmentExpression if compound assignment.
     */
    std::unique_ptr<ast::Expression> buildCompoundAssignment(
        HoocParser::AssignmentExpressionContext* ctx);

    /**
     * @brief Builds from compoundAssignment context directly.
     * @param ctx Compound assignment context.
     * @return The right-hand expression.
     */
    std::unique_ptr<ast::Expression> buildCompoundAssignmentRight(
        HoocParser::CompoundAssignmentContext* ctx);

    

    /**
     * @brief Builds a LogicalOr expression (||).
     * @param ctx Logical OR expression context.
     * @return LogicalOr expression.
     */
    std::unique_ptr<ast::Expression> buildLogicalOrExpression(HoocParser::LogicalOrExpressionContext* ctx);

    /**
     * @brief Builds a LogicalAnd expression (&&).
     * @param ctx Logical AND expression context.
     * @return LogicalAnd expression.
     */
    std::unique_ptr<ast::Expression> buildLogicalAndExpression(HoocParser::LogicalAndExpressionContext* ctx);

    /**
     * @brief Builds a RelationalExpression (==, !=, <, <=, >, >=).
     * @param ctx Relational expression context.
     * @return RelationalExpression.
     */
    std::unique_ptr<ast::Expression> buildRelationalExpression(HoocParser::RelationalExpressionContext* ctx);

    /**
     * @brief Builds an AdditiveExpression (+, -).
     * @param ctx Additive expression context.
     * @return AdditiveExpression.
     */
    std::unique_ptr<ast::Expression> buildAdditiveExpression(HoocParser::AdditiveExpressionContext* ctx);

    /**
     * @brief Builds a MultiplicativeExpression (*, /, %).
     * @param ctx Multiplicative expression context.
     * @return MultiplicativeExpression.
     */
    std::unique_ptr<ast::Expression> buildMultiplicativeExpression(HoocParser::MultiplicativeExpressionContext* ctx);

    /**
     * @brief Builds a UnaryExpression (-, !).
     * @param ctx Unary expression context.
     * @return UnaryMinus, LogicalNot, or the inner expression.
     */
    std::unique_ptr<ast::Expression> buildUnaryExpression(HoocParser::UnaryExpressionContext* ctx);

    /**
     * @brief Builds a PostfixExpression with member access, indexing, or calls.
     * @param ctx Postfix expression context.
     * @return Expression with any postfix operations applied.
     */
    std::unique_ptr<ast::Expression> buildPostfixExpression(HoocParser::PostfixExpressionContext* ctx);

    /**
     * @brief Builds a Primary expression (literals, identifiers, etc.).
     * @param ctx Primary expression context.
     * @return PrimaryExpression wrapping the appropriate Primary type.
     */
    std::unique_ptr<ast::Expression> buildPrimary(HoocParser::PrimaryContext* ctx);

    /**
     * @brief Builds an AwaitExpression (await(future)).
     * @param ctx Await expression context.
     * @return Unique pointer to AwaitExpression.
     */
    std::unique_ptr<ast::AwaitExpression> buildAwaitExpression(HoocParser::AwaitExpressionContext* ctx);

    /**
     * @brief Builds a NewObjectExpression (new ClassName(...)).
     * @param ctx New expression context.
     * @return Unique pointer to NewObjectExpression.
     */
    std::unique_ptr<ast::Expression> buildNewExpression(HoocParser::NewExpressionContext* ctx);

    // ===== Supporting Node Building =====

    /**
     * @brief Builds a Parameter from its context.
     * @param ctx Parameter context (IDENTIFIER COLON type).
     * @return Unique pointer to Parameter.
     */
    std::unique_ptr<ast::Parameter> buildParameter(HoocParser::ParameterContext* ctx);

    /**
     * @brief Builds an ArgumentList from its context.
     * @param ctx Argument list context.
     * @return Unique pointer to ArgumentList.
     */
    std::unique_ptr<ast::ArgumentList> buildArgumentList(HoocParser::ArgumentListContext* ctx);

    /**
     * @brief Builds an ArrayLiteral from a primary context.
     * @param ctx Primary context containing array literal.
     * @return Unique pointer to ArrayLiteral.
     */
    std::unique_ptr<ast::ArrayLiteral> buildArrayLiteral(HoocParser::PrimaryContext* ctx);

    /**
     * @brief Builds a TensorLiteral from a primary context.
     * @param ctx Primary context containing tensor literal.
     * @return Unique pointer to TensorLiteral.
     */
    std::unique_ptr<ast::TensorLiteral> buildTensorLiteral(HoocParser::PrimaryContext* ctx);

    /**
     * @brief Builds an ExpressionList from its context.
     * @param ctx Expression list context.
     * @return Unique pointer to ExpressionList.
     */
    std::unique_ptr<ast::ExpressionList> buildExpressionList(HoocParser::ExpressionListContext* ctx);

    // ===== Import Building =====

    /**
     * @brief Builds an ImportStatement from its context.
     * @param ctx Import statement context.
     * @return BasicImport or FromImport, or nullptr.
     */
    std::unique_ptr<ast::ImportStatement> buildImportStatement(HoocParser::ImportStatementContext* ctx);

    /**
     * @brief Builds a BasicImport (import module.path;).
     * @param ctx Basic import context.
     * @return Unique pointer to BasicImport.
     */
    std::unique_ptr<ast::BasicImport> buildBasicImport(HoocParser::BasicImportContext* ctx);

    /**
     * @brief Builds a FromImport (from module import item, item;).
     * @param ctx From import context.
     * @return Unique pointer to FromImport.
     */
    std::unique_ptr<ast::FromImport> buildFromImport(HoocParser::FromImportContext* ctx);

    /**
     * @brief Builds a ModulePath from its context.
     * @param ctx Module path context (identifiers separated by dots).
     * @return Unique pointer to ModulePath.
     */
    std::unique_ptr<ast::ModulePath> buildModulePath(HoocParser::ModulePathContext* ctx);

    /**
     * @brief Builds a QualifiedIdentifier from its context.
     * @param ctx Qualified identifier context.
     * @return Unique pointer to QualifiedIdentifier.
     */
    std::unique_ptr<ast::QualifiedIdentifier> buildQualifiedIdentifier(HoocParser::QualifiedIdentifierContext* ctx);

    /**
     * @brief Builds an ImportItem from its context.
     * @param ctx Import item context (name with optional alias).
     * @return Unique pointer to ImportItem.
     */
    std::unique_ptr<ast::ImportItem> buildImportItem(HoocParser::ImportItemContext* ctx);

    // ===== Class Building =====

    /**
     * @brief Builds a ConstructorDeclaration from its context.
     * @param ctx Constructor declaration context.
     * @return Unique pointer to ConstructorDeclaration.
     */
    std::unique_ptr<ast::ConstructorDeclaration> buildConstructorDeclaration(HoocParser::ConstructorDeclarationContext* ctx);

    /**
     * @brief Builds a ClassBody from its context.
     * @param ctx Class body context.
     * @return Unique pointer to ClassBody.
     */
    std::unique_ptr<ast::ClassBody> buildClassBody(HoocParser::ClassBodyContext* ctx);

    /**
     * @brief Builds a ClassMember from its context.
     * @param ctx Class member context (variable, constructor, or function).
     * @return ClassMember wrapping the appropriate declaration.
     */
    std::unique_ptr<ast::ClassMember> buildClassMember(HoocParser::ClassMemberContext* ctx);

    /**
     * @brief Converts a classModifier context to ClassModifier enum.
     * @param ctx Class modifier context.
     * @return The corresponding ClassModifier value.
     */
    ast::ClassModifier getClassModifier(HoocParser::ClassModifierContext* ctx);

    /**
     * @brief Rejects the 'any' meta type in positions where it is not allowed.
     * 'any' is only allowed as a function return type or inside container type
     * parameters (Map<K, V>, HashMap<K, V>). It is forbidden in variable
     * declarations, parameters, constants, and catch clauses.
     * @param type The type to check.
     * @param context Descriptive string for error message (e.g., "variable", "parameter").
     */
    void rejectAnyTypeInPosition(const ast::Type* type, const std::string& context);
};

} // namespace hooc
